CliMA/ClimaComms.jl

.github/workflows/OS-Tests.yml
Project.toml
backends/ClimaCommsMPI/src/ClimaCommsMPI.jl
backends/ClimaCommsMPI/test/Project.toml
backends/ClimaCommsMPI/test/mpi_stencil.jl
src/ClimaComms.jl
test/stencil.jl

Add "gather" capability.

---

Project.toml
backends/ClimaCommsMPI/Project.toml

Bump release to 0.1.1

---

Project.toml
backends/ClimaCommsMPI/Project.toml
backends/ClimaCommsMPI/src/ClimaCommsMPI.jl
src/ClimaComms.jl
src/neighbors.jl
test/stencil.jl

Change the layout in ClimaComms to a Dict of pid => Neighbor objects.

Change the layout in ClimaComms to a Dict of pid => Neighbor objects.

---

Project.toml
backends/ClimaCommsMPI/Project.toml

bump version to v0.3.0

---

backends/ClimaCommsMPI/Project.toml
backends/ClimaCommsMPI/src/ClimaCommsMPI.jl

I didn't realise that MPI_TAG_UB is an attribute.

hardcode tag max

---

backends/ClimaCommsMPI/src/ClimaCommsMPI.jl
docs/src/index.md
src/ClimaComms.jl
src/singleton.jl
test/stencil.jl

Add allreduce and allreduce! functions to the interface

Add allreduce and allreduce! functions to interface.

---

Project.toml
backends/ClimaCommsMPI/Project.toml
backends/ClimaCommsMPI/src/ClimaCommsMPI.jl
backends/ClimaCommsSA/Project.toml
backends/ClimaCommsSA/src/ClimaCommsSA.jl

I don't think we're using this any more.

remove KernelAbstractions

---

backends/ClimaCommsMPI/src/ClimaCommsMPI.jl
backends/ClimaCommsMPI/test/mpi_stencil.jl
src/singleton.jl
test/stencil.jl

Add a ghost buffer communication implementation using persistent MPI
----

ghost buffer communication using persistent MPI

---

backends/ClimaCommsMPI/Project.toml

Bump the version number, increase MPI.jl compat
----

Bump ClimaCommsMPI

---

backends/ClimaCommsMPI/src/ClimaCommsMPI.jl
test/stencil.jl

Add an additional constructor for MPI send/receive graph contexts.
----

Add an additional constructor for MPI send/receive graph contexts.

---

backends/ClimaCommsMPI/Project.toml

Bump ClimaCommsMPI to version 0.3.6
----

Bump ClimaCommsMPI to version 0.3.6

---

backends/ClimaCommsMPI/Project.toml
backends/ClimaCommsMPI/src/ClimaCommsMPI.jl

This should help reduce allocations in MPI operations.
----

use MPI.MultiRequest

---

backends/ClimaCommsMPI/src/ClimaCommsMPI.jl
src/singleton.jl

Add doc links for `CommsContexts`.
----

Add doc links for `CommsContexts`.

---

Project.toml
backends/ClimaCommsMPI/Project.toml

Bump versions for ClimaComms and ClimaCommsMPI.
----

Bump versions for ClimaComms and ClimaCommsMPI.

---

backends/ClimaCommsMPI/src/ClimaCommsMPI.jl
src/singleton.jl

Add type signature, additional constructors and update documentation for CommsContexts
----

Add type signature, additional constructors for CommsContexts

---

Project.toml

Part of https://github.com/CliMA/ClimaCore.jl/issues/1130
----

Support for CUDA.jl 4

---

Project.toml

Add compat entry for MPI.
----

Add compat entry for MPI.

---

Project.toml
docs/src/index.md
src/context.jl
src/mpi.jl
src/singleton.jl
test/basic.jl

add bcast op

---

docs/src/index.md
src/devices.jl
src/mpi.jl
test/basic.jl

Specify CPU threading

---

Project.toml
src/mpi.jl

Bump version to v0.5.0

---

src/devices.jl

Fix missing return in device()

---

Project.toml

This PR updates the patch version for a new release

Update patch version

---

Project.toml

As discussed on Slack, I've added the current authors (sorted by contributions)

Add authors to Project.toml

---

Project.toml
docs/src/index.md
src/context.jl
src/mpi.jl
src/singleton.jl
test/basic.jl

From: https://juliaparallel.org/MPI.jl/stable/reference/collective/#Reduce/Scan
(I still have to test it)

Add MPI.reduce!

---

.buildkite/pipeline.yml
NEWS.md
Project.toml
docs/src/index.md
ext/ClimaCommsCUDAExt.jl
src/context.jl
src/devices.jl
src/loading.jl

This PR refactors the macros to avoid code loading logic inside macros.

Refactor macros, bump patch version

---

docs/src/index.md

This PR fixes the syntax for the "note" on the index page.

Fix the note

---

NEWS.md
Project.toml
docs/Manifest.toml
docs/src/apis.md
ext/ClimaCommsCUDAExt.jl
src/ClimaComms.jl
src/adapt.jl
test/Project.toml
test/runtests.jl

This PR defines adapt for contexts and devices.

Define adapt for contexts and devices

---

NEWS.md
Project.toml

This PR bumps the version number to 0.6.7 and updates `NEWS.md`.
----

Bump to version 0.6.7

---

NEWS.md
Project.toml

This PR bumps the version number to 0.6.8 and updates `NEWS.md`.
----

Bump to version 0.6.8

---

src/logging.jl
test/logging.jl

fix: correctly set min logging level

---

.buildkite/pipeline.yml

rft: add color output to buildkite pipeline
