backends/ClimaCommsMPI/src/ClimaCommsMPI.jl

This may fix MPI failures on Windows

MPI.Finalize is called automatically by MPI.jl

---

Project.toml
backends/ClimaCommsMPI/Project.toml
backends/ClimaCommsMPI/src/ClimaCommsMPI.jl
backends/ClimaCommsMPI/test/runtests.jl

updates version numbers, allows use with MPI.jl v0.20
(this is separate from #24, which will require MPI.jl v0.20)

bump versions, increase MPI.jl compat

---

backends/ClimaCommsMPI/src/ClimaCommsMPI.jl
docs/src/index.md
src/ClimaComms.jl
src/singleton.jl

Add `device` field to CommsContext. This will help allocate resources on the appropriate device.
----

Add `device` field to CommsContext

---

src/singleton.jl

This PR
- fixes the method redefinition in `singleton.jl`
- adds a concrete type of context into the type space to avoid abstract field names
The method redefinition says:
```
[ Info: Precompiling ClimaCore [d414da3d-4745-48bb-8d80-42e94e092884]
WARNING: Method definition (::Type{ClimaComms.SingletonCommsContext})(Any) in module ClimaComms at \dev\.julia\packages\ClimaComms\3VNKq\src\singleton.jl:11 overwritten at \dev\.julia\packages\ClimaComms\3VNKq\src\singleton.jl:8.
** incremental compilation may be fatally broken for this module **
```

Fix method redefinition

---

src/mpi.jl
test/mpi_stencil.jl

Fix bug effecting non-persistent MPI communication
----

Fix bug effecting non-persistent MPI communication

---

src/mpi.jl

Check that MPI is CUDA-aware if configured as such
----

Check for CUDA-aware MPI on CUDADevice

---

.buildkite/pipeline.yml
Project.toml
docs/src/index.md
src/devices.jl

This PR adds a macro that should allow us to write, for example:
```julia
function byslab(fn, space::Spaces.AbstractSpace)
byslab(fn, ClimaComms.device(space), space)
end
function byslab(fn, device::ClimaComms.AbstractCPUDevice, space::Spaces.AbstractSpectralElementSpace)
Nh = Topologies.nlocalelems(space.topology)::Int
@inbounds begin
ClimaComms.@threaded device for h in 1:Nh
fn(SlabIndex(nothing, h))
end
end
end
```

Add threaded macro

---

.buildkite/pipeline.yml

Per:
```
┌ Warning: There are known codegen bugs on CUDA 11.4 and earlier for older GPUs like your NVIDIA Tesla P100-PCIE-16GB.
--
  | │ Please use CUDA 11.5 or later, or switch to a different device.
  | └ @ CUDA /central/scratch/esm/slurm-buildkite/climacomms-ci/87/depot/default/packages/CUDA/tVtYo/lib/cudadrv/state.jl:246
```
in [this build](https://buildkite.com/clima/climacomms-ci/builds/87#018902c3-220c-4c52-b7b4-f2b3867387c2)

Upgrade to CUDA 11.8

---

src/devices.jl
test/Project.toml
test/basic.jl
test/hygiene.jl

This PR fixes macro hygiene in the `@threaded` macro and adds a test.

Fix threaded hygiene, add test

---

docs/src/index.md
src/devices.jl
test/basic.jl
test/hygiene.jl

This PR extends `Base.@time` / `Base.@elapsed` for CPU/CUDA devices.

Extend at-time and at-elapsed

---

Project.toml
src/devices.jl
test/hygiene.jl

Found in https://buildkite.com/clima/climacoupler-ci/builds/1372#01895016-b183-41a3-93fc-fbef7e2cf455/142-211, this PR:
- Improves the macro hygiene test
- Fixes some macro hygiene issues

Fix macro hygiene

---

Project.toml
docs/src/index.md
src/devices.jl
test/hygiene.jl

This PR defines a device-flexible @sync.

Define device-flexible @sync

---

Project.toml
docs/src/index.md
src/devices.jl
test/hygiene.jl

This PR defines `ClimaComms.@cuda_sync`, which I think may actually be more useful/commonly needed/helpful than `ClimaComms.@sync`.
I've kind of explained why by updating the docs for `ClimaComms.@sync`.

Define cuda_sync macro

---

NEWS.md
docs/src/index.md
ext/ClimaCommsCUDAExt.jl
src/devices.jl
test/runtests.jl

This PR defines an `allowscalar` method, that provides a device-agnostic way to use `CUDA.@allowscalar`.
This should help us remove CUDA as a dependency in the ClimaCore test suite.

Define allowscalar

---

Project.toml
ext/ClimaCommsCUDAExt.jl
src/devices.jl
test/hygiene.jl

This PR fixes the issues with the macros, introduced in #79.
Using `sin.(AT(rand(1000, 1000)))` in the test suite:
```julia
main
julia> using Revise; include("test/hygiene.jl")
----------- @time
0.000047 seconds
this branch
julia> using Revise; include("test/hygiene.jl")
----------- @time
0.046593 seconds (97 CPU allocations: 22.891 MiB, 12.87% gc time) (6 GPU allocations: 45.776 MiB, 0.44% memmgmt time)
```
So, this appears to fix the issue. I'm not sure what the best way to test this.
Part of the reason is that this PR is technically behavior changing in that the macro now makes an argument-less closure, and times (in the case of `@time`) the closure.
I think that this is probably fine and, frankly, we could even eliminate the macro and just make the methods, which are far easier to …

Fix macros

---

NEWS.md
Project.toml
ext/ClimaCommsCUDAExt.jl
src/devices.jl

We didn't have `cuda_sync` defined in the extension, so it was falling back to the `AbstractDevice` implementation. This PR restricts that implementation, and defines the cuda extension version.
That was unfortunate. This should be a lot safer by only having `AbstractCPUDevice` support by default.

Define cuda_sync in ext, restrict cpu implementations

---

Project.toml
docs/src/index.md
ext/ClimaCommsCUDAExt.jl
src/devices.jl
test/hygiene.jl

This PR adds a device-flexible `@assert` macro, which can be used to throw errors from kernels without otherwise triggering allocations or inference failures. For a usage example, see the `column_integral_indefinite!` kernel in CliMA/ClimaCore.jl#1903.
----

Add device-flexible @assert

---

README.md
docs/make.jl
docs/src/apis.md
docs/src/faqs.md
docs/src/index.md
docs/src/internals.md
src/singleton.jl

`ClimaComms` is an important package in the `CliMA` ecosystem. In particular, it controls how users select whether to run their simulations on CPU or GPUs. It also introduces the concepts of `device` and `context` that are seen everywhere in our codes. In this PR, I try to start filling this gap.

Add documentation

---

docs/src/index.md

This PR fixes a small typo on the home page of the ClimaComms documentation.

Fix a typo

---

.buildkite/pipeline.yml
.github/workflows/JuliaFormatter.yml
.github/workflows/OS-Tests.yml
.github/workflows/docs.yml
Project.toml
docs/Manifest.toml
src/ClimaComms.jl
src/logging.jl
test/Project.toml
test/logging.jl
test/runtests.jl

This PR implements two loggers using LoggingExtras.jl. These loggers do not change the ClimaComms API.
- `MPILogger(ctx, iostream = stdout)`: This adds a ClimaComms PID prefix in front of each log message, for example `[P1]  Info: smoke test`
- `MPIFileLogger(ctx, log_dir)`: Log MPI ranks to different files within the `log_dir`.
A few questions
- Should we have a default logger constructor depending on the context? Should the MPILogger only be used if MPI is initialized?
- What should the minimal compat be for Logging? It could be set higher

Add basic MPI logging capabilities

---

docs/src/faqs.md
ext/ClimaCommsCUDAExt.jl
ext/ClimaCommsMPIExt.jl
src/devices.jl
src/mpi.jl
src/singleton.jl
test/logging.jl

This PR adds two `summary` functions to give more information to the user about the context. This will be useful for debugging MPI simulations.
Singleton context:
```
Context: SingletonCommsContext
Device: ClimaComms.CPUSingleThreaded
```
MPI Context
```
Context: MPICommsContext
Device: ClimaComms.CPUSingleThreaded
Total Processes: 4
Rank: 3, Node: clima.gps.caltech.edu
Rank: 0, Node: clima.gps.caltech.edu
Rank: 1, Node: clima.gps.caltech.edu
Rank: 2, Node: clima.gps.caltech.edu
```
MPI Context w/ CUDA
```
Context: MPICommsContext
Device: ClimaComms.CUDADevice
Total Processes: 4
Rank: 0, Local Rank: 0, Node: clima.gps.caltech.edu, Device: CUDA.CuDevice(0) (09c6a428-f4ea-8730-fd1c-f3d323d0e161)
Rank: 1, Local Rank: 1, Node: clima.gps.caltech.edu, Device: CUDA.CuDevice(0) …
```

Add `Base.summary(ctx)`, primarily to show MPI state

---

NEWS.md
Project.toml
docs/Manifest.toml
docs/Project.toml
docs/make.jl
docs/src/apis.md
docs/src/logging.md
ext/ClimaCommsMPIExt.jl
src/logging.jl
src/mpi.jl
src/singleton.jl
test/Project.toml
test/logging.jl
test/runtests.jl

This is a followup to #100.
Contents
- Added logging documentation found [here](https://clima.github.io/ClimaComms.jl/previews/PR104/logging/), this is a comprehensive page about Julia's logging basics, ClimaComms logging functionality, and some tips on using LoggingExtras directly.
- `default_logger(ctx)`, which just creates a logger that silences non-root processes. This will be useful for exchanging singleton/MPI runs without needing to change the logger. Similar [functionality](https://github.com/CliMA/ClimaAtmos.jl/blob/7bf913f3417114e33131b9632b6ee3030a489f04/src/solver/type_getters.jl#L630) exists in ClimaAtmos already and can now be removed.
- Call `default_logger` during MPI initialization
- `MPIFileLogger` has been replaced with `FileLogger(context, log_dir)`, which writes to …

Add logging documentation, `default_logger` function

---

.github/workflows/OS-Tests.yml
docs/src/index.md
ext/ClimaCommsCUDAExt.jl
src/devices.jl
test/hygiene.jl
test/runtests.jl

This PR extends `ClimaComms.@threaded` to work with `CUDADevice`, and it adds an option to control thread coarsening. This will allow us to implement simple kernels in a device-agnostic way (i.e., without needing to explicitly import CUDA). In particular, this functionality is needed to implement LU factorization and LU solver kernels in CliMA/ClimaAtmos.jl#2730. It can also be used to generalize most of the kernels defined in `ClimaCoreCUDAExt.jl` to multi-threaded CPUs.
The current implementation of this macro only performs simple one-dimensional parallelization, but it can be extended to support shared memory and multi-dimensional thread/block configurations in the future. Eventually, we might be able to eliminate CUDA extensions from other packages altogether, replacing them with …

Extend threaded macro to CUDADevice

---

docs/src/apis.md
ext/ClimaCommsCUDAExt.jl
src/devices.jl
test/runtests.jl
test/threaded_benchmark.jl

This PR extends the threaded macro to support lazy iterators from `Base` and `Base.Iterators`, such as `reverse`, `enumerate`, `zip`, and generator expressions. To enable threading over multiple iterators, support is also added for `Iterators.product`, with linear-to-Cartesian index conversion performed using standard integer division on CPUs and `Base.multiplicativeinverse` on GPUs. A new benchmarking script is also added to the test suite, which will allow us to monitor the performance of ClimaCore-like kernels.
One feature required for CliMA/ClimaAtmos.jl#3827 is the ability to parallelize over an iterator of the form `Iterators.partition(enumerate(Iterators.flatten(...)), autodiff_batch_size)`, which this PR will allow us to do.
----

Extend threaded macro to support lazy iterators
